// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Entity
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject entityMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Entity";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TestEnum("TestEnum"),
		IntToAdd("IntToAdd"),
		DecToAdd("DecToAdd");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Entity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Entity"));
	}

	protected Entity(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject entityMendixObject)
	{
		if (entityMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Entity", entityMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Entity");

		this.entityMendixObject = entityMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Entity.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Entity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Entity.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Entity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Entity(context, mendixObject);
	}

	public static myfirstmodule.proxies.Entity load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Entity.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Entity> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Entity> result = new java.util.ArrayList<myfirstmodule.proxies.Entity>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Entity" + xpathConstraint))
			result.add(myfirstmodule.proxies.Entity.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of TestEnum
	 * @param testenum
	 */
	public final myfirstmodule.proxies.TestEnum getTestEnum()
	{
		return getTestEnum(getContext());
	}

	/**
	 * @param context
	 * @return value of TestEnum
	 */
	public final myfirstmodule.proxies.TestEnum getTestEnum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TestEnum.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.TestEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TestEnum
	 * @param testenum
	 */
	public final void setTestEnum(myfirstmodule.proxies.TestEnum testenum)
	{
		setTestEnum(getContext(), testenum);
	}

	/**
	 * Set value of TestEnum
	 * @param context
	 * @param testenum
	 */
	public final void setTestEnum(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.TestEnum testenum)
	{
		if (testenum != null)
			getMendixObject().setValue(context, MemberNames.TestEnum.toString(), testenum.toString());
		else
			getMendixObject().setValue(context, MemberNames.TestEnum.toString(), null);
	}

	/**
	 * @return value of IntToAdd
	 */
	public final java.lang.Integer getIntToAdd()
	{
		return getIntToAdd(getContext());
	}

	/**
	 * @param context
	 * @return value of IntToAdd
	 */
	public final java.lang.Integer getIntToAdd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.IntToAdd.toString());
	}

	/**
	 * Set value of IntToAdd
	 * @param inttoadd
	 */
	public final void setIntToAdd(java.lang.Integer inttoadd)
	{
		setIntToAdd(getContext(), inttoadd);
	}

	/**
	 * Set value of IntToAdd
	 * @param context
	 * @param inttoadd
	 */
	public final void setIntToAdd(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer inttoadd)
	{
		getMendixObject().setValue(context, MemberNames.IntToAdd.toString(), inttoadd);
	}

	/**
	 * @return value of DecToAdd
	 */
	public final java.math.BigDecimal getDecToAdd()
	{
		return getDecToAdd(getContext());
	}

	/**
	 * @param context
	 * @return value of DecToAdd
	 */
	public final java.math.BigDecimal getDecToAdd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.DecToAdd.toString());
	}

	/**
	 * Set value of DecToAdd
	 * @param dectoadd
	 */
	public final void setDecToAdd(java.math.BigDecimal dectoadd)
	{
		setDecToAdd(getContext(), dectoadd);
	}

	/**
	 * Set value of DecToAdd
	 * @param context
	 * @param dectoadd
	 */
	public final void setDecToAdd(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal dectoadd)
	{
		getMendixObject().setValue(context, MemberNames.DecToAdd.toString(), dectoadd);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return entityMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Entity that = (myfirstmodule.proxies.Entity) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Entity";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
